### ISSUE TITLE
[Widgets] Pop up odd formatting issue

### ISSUE THREAD

**Issue by soobinchoi54** [macmods/sfi#82] opened 2020-12-05 00:05 UTC
Steps to reproduce: 
Click on any feature on the map and find that the popup displays weirdly 

<img width="1087" alt="Screen Shot 2020-12-04 at 4 02 49 PM" src="https://user-images.githubusercontent.com/41706004/101226728-44855280-364a-11eb-9582-c361d69f1b74.png">
<img width="954" alt="Screen Shot 2020-12-04 at 4 02 38 PM" src="https://user-images.githubusercontent.com/41706004/101226729-464f1600-364a-11eb-8057-ca9bfd918f3c.png">

Expected result: 
<img width="728" alt="Screen Shot 2020-12-04 at 4 04 38 PM" src="https://user-images.githubusercontent.com/41706004/101226774-6b438900-364a-11eb-97d6-13483cd6e2b5.png">

**Comment by Danny7226** [comment] 2020-12-07 20:45
I noticed that the bottom of the popup is always attached to the points where the user clicked, and the top of the popup is always gaped by 15px from the top of the web window (as below)
![Screen Shot 2020-12-07 at 12 42 36](https://user-images.githubusercontent.com/28212783/101403428-15f5ba80-388a-11eb-9710-6002cc592ab5.png)


I think it is due to the 77th line of the `main.css` which is marked as `!important` 
![Screen Shot 2020-12-07 at 12 42 19](https://user-images.githubusercontent.com/28212783/101403442-1aba6e80-388a-11eb-90f8-592b971df884.png)

**Comment by Danny7226** [comment] 2020-12-07 21:50
**The issue is caused by line 77 of `main.css`**
* This line of code was supposed to shift down the web window by 15px.
    * line 77 is not specific enough to target only the web window. As a result, it overrides other elements that we didn't expect.
    * This issue is resolved by this [PR](https://github.com/macmods/sfi/compare/popupfix?expand=1)
    * Will close the issue after the merge of the PR

**Closed** 2020-12-07 22:38 UTC
Labels: bug
